<?php

namespace Proxies\__CG__\Project\LineOfWorkBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Phrase extends \Project\LineOfWorkBundle\Entity\Phrase implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'id', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'main_header', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'medium_header', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'medium_paragraph', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'bottom_paragraph');
        }

        return array('__isInitialized__', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'id', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'main_header', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'medium_header', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'medium_paragraph', '' . "\0" . 'Project\\LineOfWorkBundle\\Entity\\Phrase' . "\0" . 'bottom_paragraph');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Phrase $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainHeader($mainHeader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainHeader', array($mainHeader));

        return parent::setMainHeader($mainHeader);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainHeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainHeader', array());

        return parent::getMainHeader();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediumHeader($mediumHeader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediumHeader', array($mediumHeader));

        return parent::setMediumHeader($mediumHeader);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediumHeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediumHeader', array());

        return parent::getMediumHeader();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediumParagraph($mediumParagraph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediumParagraph', array($mediumParagraph));

        return parent::setMediumParagraph($mediumParagraph);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediumParagraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediumParagraph', array());

        return parent::getMediumParagraph();
    }

    /**
     * {@inheritDoc}
     */
    public function setBottomParagraph($bottomParagraph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBottomParagraph', array($bottomParagraph));

        return parent::setBottomParagraph($bottomParagraph);
    }

    /**
     * {@inheritDoc}
     */
    public function getBottomParagraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBottomParagraph', array());

        return parent::getBottomParagraph();
    }

}
